export interface CourseInterface {
    _id:any,
    degreeProgram:String,
    session:String,
    semester:String,
    courseTitle:String,
    courseCode:String,
    creditHours:String,
    pre:String,
    quiz:String,
    midTerm:String,
    finalTerm:String,
    assignment:String,
    lab:String,
    totalMarks:String,
    courseCoordinator:String,
    url:String,
    currentCatelogDescription:String,
    textBook:String,
    referenceMaterial:String,
    courseGoals:String

    // "_id": "5ddfc13d92eb1e27640b42b2",
    //     "degprog": "MCS",
    //     "session": "2017-21",
    //     "semester": "2nd",
    //     "c_code": "55",
    //     "c_title": "SE",
    //     "c_hours": "4234",
    //     "m_quiz": 30,
    //     "m_assign": 20,
    //     "c_coordinator": "Ali Abbas",
    //     "c_url": "www.CsinBestWay.com",
    //     "c_catelog": "catelog dont know",
    //     "c_tbook": "Cs In BestWay",
    //     "c_reference": "CsinBestWay",
    //     "c_goals": "To understand students ",
    //     "c_pre": "Special None",
    //     "m_lab": null,
    //     "m_mid": 75,
    //     "m_final": 75,
    //     "m_total": 200,
    
        
}
